-- MySQL Script generated by MySQL Workbench
-- Fri May 26 19:01:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema documentprocessorapp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `documentprocessorapp` ;

-- -----------------------------------------------------
-- Schema documentprocessorapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `documentprocessorapp` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `documentprocessorapp` ;

-- -----------------------------------------------------
-- Table `documentprocessorapp`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `documentprocessorapp`.`client` ;

CREATE TABLE IF NOT EXISTS `documentprocessorapp`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `clientName` VARCHAR(200) NULL DEFAULT NULL,
  `mail` VARCHAR(200) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `mail` ON `documentprocessorapp`.`client` (`mail` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `documentprocessorapp`.`filetype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `documentprocessorapp`.`filetype` ;

CREATE TABLE IF NOT EXISTS `documentprocessorapp`.`filetype` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `typeName` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `documentprocessorapp`.`file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `documentprocessorapp`.`file` ;

CREATE TABLE IF NOT EXISTS `documentprocessorapp`.`file` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL DEFAULT NULL,
  `path` VARCHAR(255) NULL DEFAULT NULL,
  `typeId` INT NULL DEFAULT NULL,
  `clientId` INT NULL DEFAULT NULL,
  `lastModfied` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `file_ibfk_1`
    FOREIGN KEY (`typeId`)
    REFERENCES `documentprocessorapp`.`filetype` (`id`),
  CONSTRAINT `file_ibfk_2`
    FOREIGN KEY (`clientId`)
    REFERENCES `documentprocessorapp`.`client` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `typeId` ON `documentprocessorapp`.`file` (`typeId` ASC) VISIBLE;

CREATE INDEX `clientId` ON `documentprocessorapp`.`file` (`clientId` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;